### ISSUE TITLE
Doesn't build on Windows...

### ISSUE THREAD

**Issue by photex** [wycats/rust-civet#8]
Hi folks!

I was hoping to contribute an update to build.rs that would add the ability to build civet-sys on Windows when using the MSVC toolchain. Civetweb has a solution for visual studio builds in the [current release](https://github.com/civetweb/civetweb/tree/v1.8), and it can be built with: `msbuild /p:Configuration=Release /p:Platform=x64 VisualStudio/civetweb.sln`

The platform could also be win32 instead.

I'm guessing that when building with the gnu toolchain it may perhaps just work as it is. Is there a cfg specifically for msvc builds when using cargo?

**Comment by alexcrichton** [comment]
Ah yeah we can probably easily add detection of MSVC vs MinGW by just checking for "msvc" in `$TARGET`, wanna send a PR for this?

**Comment by photex** [comment]
Sure thing; I'll dig in and see if I can work it out.
